### ISSUE TITLE
Incompatible with Sodium?

### ISSUE THREAD

**Issue by Dorsall** [jaredlll08/TipTheScales#26] opened 2023-03-08 09:51 UTC
doesn't seem like i can access any features with sodium's revamped video settings menu. is there any way to get around this? 
1.19.3

**Comment by jaredlll08** [comment] 2023-03-08 20:21
When you say you can't access any features, do you mean features of sodium, or features of TipTheScales?

**Comment by PablloOswalld** [comment] 2023-04-10 15:49
using it with Rubidium which is a forge sodium fork, which also has the revamped options menu, i cant use the TipTheScales feature, the gui scale is the vanilla one and nothing changed, just the base game 3 options.

**Comment by jaredlll08** [comment] 2023-04-10 15:59
TipTheScales is not compatible with ***any*** mod that replaces the options screen.

I don't want to play whack-a-mole with all the different sodium clones, so the whole mod gets a blanket compatibility ban.

Now what shouldn't happen, is a crash, it should just do nothing, which from the sounds of it is what is happening, the mod doesn't crash, but it doesn't do anything, so everything is working as intended.

@Dorsall please can you confirm what you are experiencing so this issue can be resolved.

**Comment by illa4257** [comment] 2023-04-21 22:53
In Fabric 1.19.3 it doesn't do anything. Conclusion: Incompatible with Fabric 1.19.3.

**Comment by illa4257** [comment] 2023-04-21 23:12
In Fabric 1.19.3 it doesn't do anything.

Info:
- Version: 1.19.3
- Fabric Loader: 0.14.19
- Java: OpenJDK 17.0.2, OpenJDK 19.0.1

Mods:
- Fabric API: 0.76.1
- TipTheScales: 6.0.11

**Comment by jaredlll08** [comment] 2023-05-09 15:29
Going to close this due to no reply from @Dorsall.

If anyone has an actual crash between my mod and Sodium, please feel free to make a github issue and I will make sure it doesn't crash.

**Closed as not planned by jaredlll08** 2023-05-09 15:29 UTC
