### ISSUE TITLE
Support for Sodium

### ISSUE THREAD

**Issue by MbtMarco** [jaredlll08/TipTheScales#30] opened 2023-09-24 11:21 UTC
Well you might wonder why. Nowadays you can't play Minecraft without Optfine or Sodium because it's optimized like crap. I understand maybe Optifine is closed source but Sodium is not. Honestly, your mod can be very useful in some cases but due to its incompatibility with Sodium it makes it unusable for most Minecraft users.

**Comment by jaredlll08** [comment] 2023-09-24 11:23
Duplicate of https://github.com/jaredlll08/TipTheScales/issues/26

**Closed as not planned by jaredlll08** 2023-09-24 11:23 UTC
