### ISSUE TITLE
Mod does nothing

### ISSUE THREAD

**Issue by LuciusofLegend** [jaredlll08/TipTheScales#18] opened 2022-03-17 16:26 UTC
I simply see no change with this mod installed.  I am running fabric 1.18.1 and at first I accidentally downloaded the forge version but then I made sure to download the fabric one.  I have about 55 client side mods and I suspected that sodium might have overridden the mod with it's changes to the video settings screen, so I installed 'better sodium video settings button' which keeps the vanilla video settings screen except for a button in the bottom right that takes you to the sodium menu.  After that I tried with this mod being the only mod.  Fabtic 1.13.3 Minecraft 1.18.1 I downloaded this file [TipTheScales Fabric 1.18.1](https://www.curseforge.com/minecraft/mc-mods/tipthescales/download/3649236).  Nothing changed.  The gui scale slider is exactly the same as always.

**Comment by jaredlll08** [comment] 2022-03-17 16:59
> The gui scale slider is exactly the same as always.

Can you upload a video showing how it looks please.

**Comment by LuciusofLegend** [comment] 2022-03-17 18:47
Ok.

**Comment by LuciusofLegend** [comment] 2022-03-17 18:52
Wait.  Have to try one thing.  It does't explain it not working in my modpack but it may explain why it didn't work on its own.  I didn't add fabric api when it was all by itself.  [Edit]  Wait, wouldn't that crash it though?

**Comment by LuciusofLegend** [comment] 2022-03-17 19:05
Nope, added fabric api and mod menu.  Did not fix.  I don't know if I will be able to send you a video but here is a screenshot of the mod menu and all the GUI scales:
![Mods](https://user-images.githubusercontent.com/83921153/158876377-03c608c2-5546-4b24-8648-6f7725f2ff57.png
![GUI Scale Auto](https://user-images.githubusercontent.com/83921153/158877100-b118ceec-bd5e-44ed-bc18-2e91ce5d1371.png)
![GUI Scale 1](https://user-images.githubusercontent.com/83921153/158877138-42de44e1-90cf-4fa9-a9bc-94d2c6485d51.png)
![GUI Scale 2](https://user-images.githubusercontent.com/83921153/158877168-15a9674d-6063-43e0-9c45-516b6aaa0bf4.png)
![GUI Scale 3](https://user-images.githubusercontent.com/83921153/158877198-693a573a-675e-4839-b989-b1a80e6ea1d4.png)
![GUI Scale 4](https://user-images.githubusercontent.com/83921153/158877225-e08371ed-7d7f-4c96-a5af-a1cdcb59ce76.png)
)

**Comment by LuciusofLegend** [comment] 2022-03-17 19:06
I know this may not be the most helpful form of debugging but I just can't think of anything else I can do.

**Comment by jaredlll08** [comment] 2022-03-17 19:10
What screen size are you playing on?

**Comment by LuciusofLegend** [comment] 2022-03-17 19:12
15.6 inch 1920x1080

**Comment by LuciusofLegend** [comment] 2022-03-17 19:13
I'll be able to upload a video in a min.

**Comment by jaredlll08** [comment] 2022-03-17 19:15
okay, so from the screenshots you posted, the mod seems to be working perfectly.

If you uninstall the mod, you'll notice that you don't get a slider, you have a button that you press to change the size, all the mod does on current versions is add the slider so you don't need to constantly move your mouse to find the button.

**Comment by LuciusofLegend** [comment] 2022-03-17 19:16
Oh.  I thought it added more notches like better gui scaling.  Sorry for the confusion.

**Comment by jaredlll08** [comment] 2022-03-17 19:19
Nope, in previous versions *before* mojang added all the gui scale options, it did let people select the hidden ones, but nowadays it is only for adding a slider instead of the buttons.

Unfortunately the way that scaling is done, it is not exactly simple to add more options (like 3.5).

Going to close this because the mod does appear to be working as intended.

**Closed as completed by jaredlll08** 2022-03-17 19:19 UTC
